package BLEScut;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BEACON.
 */
public class Beacon implements java.io.Serializable {

    private Long id;
    private String proximityUuid;
    private String major;
    private String minor;
    private String longitude;
    private String latitude;
    private String uniqueId;
    private String imageUrl;
    private String name;
    private String description;
    private String content;
    private String subscriptions_count;
    private boolean isSubscripted;

    public Beacon() {
    }

    public Beacon(Long id) {
        this.id = id;
    }

    public Beacon(Long id, String proximityUuid, String major, String minor, String longitude, String latitude, String uniqueId, String imageUrl, String name, String description, String content, String subscriptions_count, boolean isSubscripted) {
        this.id = id;
        this.proximityUuid = proximityUuid;
        this.major = major;
        this.minor = minor;
        this.longitude = longitude;
        this.latitude = latitude;
        this.uniqueId = uniqueId;
        this.imageUrl = imageUrl;
        this.name = name;
        this.description = description;
        this.content = content;
        this.subscriptions_count = subscriptions_count;
        this.isSubscripted = isSubscripted;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProximityUuid() {
        return proximityUuid;
    }

    public void setProximityUuid(String proximityUuid) {
        this.proximityUuid = proximityUuid;
    }

    public String getMajor() {
        return major;
    }

    public void setMajor(String major) {
        this.major = major;
    }

    public String getMinor() {
        return minor;
    }

    public void setMinor(String minor) {
        this.minor = minor;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getUniqueId() {
        return uniqueId;
    }

    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getSubscriptions_count() {
        return subscriptions_count;
    }

    public void setSubscriptions_count(String subscriptions_count) {
        this.subscriptions_count = subscriptions_count;
    }

    public boolean getIsSubscripted() {
        return isSubscripted;
    }

    public void setIsSubscripted(boolean isSubscripted) {
        this.isSubscripted = isSubscripted;
    }

}
