package BLEScut;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CARD.
 */
public class Card implements java.io.Serializable {

    private Long id;
    private String card_id;
    private String beacon_id;
    private String beacon_name;
    private String beacon_avatar;
    private String title;
    private String slug;
    private String cover_url;
    private String content;
    private String favorites_count;
    private String comments_count;

    public Card() {
    }

    public Card(Long id) {
        this.id = id;
    }

    public Card(Long id, String card_id, String beacon_id, String beacon_name, String beacon_avatar, String title, String slug, String cover_url, String content, String favorites_count, String comments_count) {
        this.id = id;
        this.card_id = card_id;
        this.beacon_id = beacon_id;
        this.beacon_name = beacon_name;
        this.beacon_avatar = beacon_avatar;
        this.title = title;
        this.slug = slug;
        this.cover_url = cover_url;
        this.content = content;
        this.favorites_count = favorites_count;
        this.comments_count = comments_count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCard_id() {
        return card_id;
    }

    public void setCard_id(String card_id) {
        this.card_id = card_id;
    }

    public String getBeacon_id() {
        return beacon_id;
    }

    public void setBeacon_id(String beacon_id) {
        this.beacon_id = beacon_id;
    }

    public String getBeacon_name() {
        return beacon_name;
    }

    public void setBeacon_name(String beacon_name) {
        this.beacon_name = beacon_name;
    }

    public String getBeacon_avatar() {
        return beacon_avatar;
    }

    public void setBeacon_avatar(String beacon_avatar) {
        this.beacon_avatar = beacon_avatar;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getCover_url() {
        return cover_url;
    }

    public void setCover_url(String cover_url) {
        this.cover_url = cover_url;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getFavorites_count() {
        return favorites_count;
    }

    public void setFavorites_count(String favorites_count) {
        this.favorites_count = favorites_count;
    }

    public String getComments_count() {
        return comments_count;
    }

    public void setComments_count(String comments_count) {
        this.comments_count = comments_count;
    }

}
