package BLEScut;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import BLEScut.Beacon;
import BLEScut.Card;

import BLEScut.BeaconDao;
import BLEScut.CardDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig beaconDaoConfig;
    private final DaoConfig cardDaoConfig;

    private final BeaconDao beaconDao;
    private final CardDao cardDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        beaconDaoConfig = daoConfigMap.get(BeaconDao.class).clone();
        beaconDaoConfig.initIdentityScope(type);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        beaconDao = new BeaconDao(beaconDaoConfig, this);
        cardDao = new CardDao(cardDaoConfig, this);

        registerDao(Beacon.class, beaconDao);
        registerDao(Card.class, cardDao);
    }
    
    public void clear() {
        beaconDaoConfig.getIdentityScope().clear();
        cardDaoConfig.getIdentityScope().clear();
    }

    public BeaconDao getBeaconDao() {
        return beaconDao;
    }

    public CardDao getCardDao() {
        return cardDao;
    }

}
